// Test data only: responses of the sandbox shop (WooCommerce 11.2.1) as it sent them, every key included, so the
// tests read what the API really sends. Every person in them is invented (see sandbox/php/seed.php).

type Json = Record<string, unknown>

/** `GET orders/39`: several lines (two of them variations), a coupon, a company, a parcel sent to somebody else. */
const order: Json = {
  id: 39,
  parent_id: 0,
  status: 'processing',
  currency: 'PLN',
  version: '11.2.1',
  prices_include_tax: true,
  date_created: '2026-09-21T09:20:00',
  date_modified: '2026-10-10T21:01:48',
  discount_total: '8.14',
  discount_tax: '1.87',
  shipping_total: '12.19',
  shipping_tax: '2.80',
  cart_tax: '77.03',
  total: '426.96',
  total_tax: '79.83',
  customer_id: 0,
  order_key: 'wc_order_SampleOrderKey',
  billing: {
    first_name: 'Ewa',
    last_name: 'Fikcyjna',
    company: 'Fikcyjna Firma Sp. z o.o.',
    address_1: 'ul. Wymyślona 22',
    address_2: '',
    city: 'Wrocław',
    state: '',
    postcode: '50-001',
    country: 'PL',
    email: 'ewa.fikcyjna@example.test',
    phone: '+48 000 000 104',
  },
  shipping: {
    first_name: 'Marek',
    last_name: 'Odbiorca',
    company: 'Fikcyjna Firma Sp. z o.o. Magazyn',
    address_1: 'ul. Magazynowa 5',
    address_2: '',
    city: 'Łódź',
    state: '',
    postcode: '90-001',
    country: 'PL',
    phone: '+48 000 000 106',
  },
  payment_method: 'przelewy24',
  payment_method_title: 'Przelewy24',
  transaction_id: 'SANDBOX-TXN-0009',
  customer_ip_address: '192.0.2.19',
  customer_user_agent: 'HanzaSandboxBrowser/1.0',
  created_via: 'sandbox',
  customer_note: '',
  date_completed: null,
  date_paid: '2026-09-21T09:22:00',
  cart_hash: '',
  number: '39',
  meta_data: [],
  line_items: [
    {
      id: 26,
      name: 'Koszulka testowa - S',
      product_id: 19,
      variation_id: 20,
      quantity: 2,
      tax_class: '',
      subtotal: '128.46',
      subtotal_tax: '29.54',
      total: '126.13',
      total_tax: '29.01',
      taxes: [{ id: 1, total: '29.01', subtotal: '29.54' }],
      meta_data: [
        { id: 184, key: 'rozmiar', value: 'S', display_key: 'Rozmiar', display_value: 'S' },
        { id: 227, key: '_reduced_stock', value: '2', display_key: '_reduced_stock', display_value: '2' },
      ],
      sku: 'WOO-TSHIRT-S',
      global_unique_id: '',
      price: 63.065041,
      image: { id: 0, src: '' },
      parent_name: 'Koszulka testowa',
    },
    {
      id: 27,
      name: 'Koszulka testowa - M',
      product_id: 19,
      variation_id: 21,
      quantity: 1,
      tax_class: '',
      subtotal: '64.23',
      subtotal_tax: '14.77',
      total: '63.07',
      total_tax: '14.50',
      taxes: [{ id: 1, total: '14.50', subtotal: '14.77' }],
      meta_data: [
        { id: 194, key: 'rozmiar', value: 'M', display_key: 'Rozmiar', display_value: 'M' },
        { id: 228, key: '_reduced_stock', value: '1', display_key: '_reduced_stock', display_value: '1' },
      ],
      sku: 'WOO-TSHIRT',
      global_unique_id: '',
      price: 63.06504,
      image: { id: 0, src: '' },
      parent_name: 'Koszulka testowa',
    },
    {
      id: 28,
      name: 'Kubek ceramiczny żółty',
      product_id: 10,
      variation_id: 0,
      quantity: 3,
      tax_class: '',
      subtotal: '121.93',
      subtotal_tax: '28.04',
      total: '118.44',
      total_tax: '27.24',
      taxes: [{ id: 1, total: '27.24', subtotal: '28.04' }],
      meta_data: [{ id: 229, key: '_reduced_stock', value: '3', display_key: '_reduced_stock', display_value: '3' }],
      sku: 'WOO-MUG-1',
      global_unique_id: '',
      price: 39.47967466666667,
      image: { id: '', src: '' },
      parent_name: null,
    },
    {
      id: 29,
      name: 'Plakat bez SKU',
      product_id: 12,
      variation_id: 0,
      quantity: 1,
      tax_class: '',
      subtotal: '28.46',
      subtotal_tax: '6.54',
      total: '27.30',
      total_tax: '6.28',
      taxes: [{ id: 1, total: '6.28', subtotal: '6.54' }],
      meta_data: [{ id: 230, key: '_reduced_stock', value: '1', display_key: '_reduced_stock', display_value: '1' }],
      sku: '',
      global_unique_id: '',
      price: 27.300813,
      image: { id: '', src: '' },
      parent_name: null,
    },
  ],
  tax_lines: [
    {
      id: 30,
      rate_code: 'PL-VAT-1',
      rate_id: 1,
      label: 'VAT',
      compound: false,
      tax_total: '77.03',
      shipping_tax_total: '2.80',
      rate_percent: 23,
      meta_data: [],
    },
  ],
  shipping_lines: [
    {
      id: 31,
      method_title: 'Kurier testowy',
      method_id: 'flat_rate',
      instance_id: '',
      total: '12.19',
      total_tax: '2.80',
      taxes: [{ id: 1, total: '2.80', subtotal: '' }],
      tax_status: 'taxable',
      meta_data: [],
    },
  ],
  fee_lines: [],
  coupon_lines: [
    {
      id: 32,
      code: 'test10',
      discount: '8.13',
      discount_tax: '1.87',
      meta_data: [
        {
          id: 226,
          key: 'coupon_info',
          value: '[29,"test10",null,10]',
          display_key: 'coupon_info',
          display_value: '[29,"test10",null,10]',
        },
      ],
      discount_type: 'fixed_cart',
      nominal_amount: 10,
      free_shipping: false,
    },
  ],
  refunds: [],
  payment_url: 'https://shop.example.test/checkout/order-pay/39/?pay_for_order=true&key=wc_order_SampleOrderKey',
  is_editable: false,
  needs_payment: false,
  needs_processing: true,
  date_created_gmt: '2026-09-21T07:20:00',
  date_modified_gmt: '2026-10-10T19:01:48',
  date_completed_gmt: null,
  date_paid_gmt: '2026-09-21T07:22:00',
  currency_symbol: 'zł',
  _links: {
    self: [
      {
        href: 'https://shop.example.test/wp-json/wc/v3/orders/39',
        targetHints: { allow: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'] },
      },
    ],
    collection: [{ href: 'https://shop.example.test/wp-json/wc/v3/orders' }],
    email_templates: [{ embeddable: true, href: 'https://shop.example.test/wp-json/wc/v3/orders/39/actions/email_templates' }],
  },
}

/** `GET products/10`: a simple product that manages its stock. */
const simpleProduct: Json = {
  id: 10,
  name: 'Kubek ceramiczny żółty',
  slug: 'kubek-ceramiczny-zolty',
  permalink: 'https://shop.example.test/product/kubek-ceramiczny-zolty/',
  date_created: '2026-10-10T21:01:44',
  date_created_gmt: '2026-10-10T19:01:44',
  date_modified: '2026-10-10T21:01:52',
  date_modified_gmt: '2026-10-10T19:01:52',
  type: 'simple',
  status: 'publish',
  featured: false,
  catalog_visibility: 'visible',
  description: '',
  short_description: '',
  sku: 'WOO-MUG-1',
  price: '49.99',
  regular_price: '49.99',
  sale_price: '',
  date_on_sale_from: null,
  date_on_sale_from_gmt: null,
  date_on_sale_to: null,
  date_on_sale_to_gmt: null,
  on_sale: false,
  purchasable: true,
  total_sales: 11,
  virtual: false,
  downloadable: false,
  downloads: [],
  download_limit: -1,
  download_expiry: -1,
  external_url: '',
  button_text: '',
  tax_status: 'taxable',
  tax_class: '',
  manage_stock: true,
  stock_quantity: 89,
  backorders: 'no',
  backorders_allowed: false,
  backordered: false,
  low_stock_amount: null,
  sold_individually: false,
  weight: '',
  dimensions: { length: '', width: '', height: '' },
  shipping_required: true,
  shipping_taxable: true,
  shipping_class: '',
  shipping_class_id: 0,
  reviews_allowed: true,
  average_rating: '0.00',
  rating_count: 0,
  upsell_ids: [],
  cross_sell_ids: [],
  parent_id: 0,
  purchase_note: '',
  categories: [{ id: 15, name: 'Uncategorized', slug: 'uncategorized' }],
  brands: [],
  tags: [],
  images: [],
  attributes: [],
  default_attributes: [],
  variations: [],
  grouped_products: [],
  menu_order: 0,
  price_html: '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol" translate="no" dir="auto">&#122;&#322;</span>49.99</bdi></span>',
  related_ids: [28, 11, 15, 17, 12],
  meta_data: [],
  stock_status: 'instock',
  has_options: false,
  post_password: '',
  global_unique_id: '',
  _links: {
    self: [
      {
        href: 'https://shop.example.test/wp-json/wc/v3/products/10',
        targetHints: { allow: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'] },
      },
    ],
    collection: [{ href: 'https://shop.example.test/wp-json/wc/v3/products' }],
  },
}

/** `GET products/19`: a variable product with four variations. */
const variableProduct: Json = {
  id: 19,
  name: 'Koszulka testowa',
  slug: 'koszulka-testowa',
  permalink: 'https://shop.example.test/product/koszulka-testowa/',
  date_created: '2026-10-10T21:01:45',
  date_created_gmt: '2026-10-10T19:01:45',
  date_modified: '2026-10-10T21:01:52',
  date_modified_gmt: '2026-10-10T19:01:52',
  type: 'variable',
  status: 'publish',
  featured: false,
  catalog_visibility: 'visible',
  description: '',
  short_description: '',
  sku: 'WOO-TSHIRT',
  price: '79.00',
  regular_price: '',
  sale_price: '',
  date_on_sale_from: null,
  date_on_sale_from_gmt: null,
  date_on_sale_to: null,
  date_on_sale_to_gmt: null,
  on_sale: false,
  purchasable: true,
  total_sales: 3,
  virtual: false,
  downloadable: false,
  downloads: [],
  download_limit: -1,
  download_expiry: -1,
  external_url: '',
  button_text: '',
  tax_status: 'taxable',
  tax_class: '',
  manage_stock: true,
  stock_quantity: 40,
  backorders: 'no',
  backorders_allowed: false,
  backordered: false,
  low_stock_amount: null,
  sold_individually: false,
  weight: '',
  dimensions: { length: '', width: '', height: '' },
  shipping_required: true,
  shipping_taxable: true,
  shipping_class: '',
  shipping_class_id: 0,
  reviews_allowed: true,
  average_rating: '0.00',
  rating_count: 0,
  upsell_ids: [],
  cross_sell_ids: [],
  parent_id: 0,
  purchase_note: '',
  categories: [{ id: 15, name: 'Uncategorized', slug: 'uncategorized' }],
  brands: [],
  tags: [],
  images: [],
  attributes: [
    {
      id: 0,
      name: 'Rozmiar',
      slug: 'Rozmiar',
      position: 0,
      visible: true,
      variation: true,
      options: ['S', 'M', 'L', 'XL'],
    },
  ],
  default_attributes: [],
  variations: [20, 21, 22, 23],
  grouped_products: [],
  menu_order: 0,
  price_html: '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol" translate="no" dir="auto">&#122;&#322;</span>79.00</bdi></span>',
  related_ids: [24, 12, 27, 11, 10],
  meta_data: [],
  stock_status: 'instock',
  has_options: true,
  post_password: '',
  global_unique_id: '',
  _links: {
    self: [
      {
        href: 'https://shop.example.test/wp-json/wc/v3/products/19',
        targetHints: { allow: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'] },
      },
    ],
    collection: [{ href: 'https://shop.example.test/wp-json/wc/v3/products' }],
  },
}

/** `GET products/19/variations/21`: a variation without a SKU of its own, so it reports its parent's. */
const variation: Json = {
  id: 21,
  type: 'variation',
  date_created: '2026-10-10T21:01:45',
  date_created_gmt: '2026-10-10T19:01:45',
  date_modified: '2026-10-10T21:01:48',
  date_modified_gmt: '2026-10-10T19:01:48',
  description: '',
  permalink: 'https://shop.example.test/product/koszulka-testowa/?attribute_rozmiar=M',
  sku: 'WOO-TSHIRT',
  global_unique_id: '',
  price: '79.00',
  regular_price: '79.00',
  sale_price: '',
  date_on_sale_from: null,
  date_on_sale_from_gmt: null,
  date_on_sale_to: null,
  date_on_sale_to_gmt: null,
  on_sale: false,
  status: 'publish',
  purchasable: true,
  virtual: false,
  downloadable: false,
  downloads: [],
  download_limit: -1,
  download_expiry: -1,
  tax_status: 'taxable',
  tax_class: '',
  manage_stock: true,
  stock_quantity: 4,
  stock_status: 'instock',
  backorders: 'no',
  backorders_allowed: false,
  backordered: false,
  low_stock_amount: null,
  weight: '',
  dimensions: { length: '', width: '', height: '' },
  shipping_class: '',
  shipping_class_id: 0,
  image: null,
  gallery_image_ids: [],
  attributes: [{ id: 0, name: 'Rozmiar', slug: 'rozmiar', option: 'M' }],
  menu_order: 0,
  meta_data: [],
  name: 'M',
  parent_id: 19,
  _links: {
    self: [
      {
        href: 'https://shop.example.test/wp-json/wc/v3/products/19/variations/21',
        targetHints: { allow: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'] },
      },
    ],
    collection: [{ href: 'https://shop.example.test/wp-json/wc/v3/products/19/variations' }],
    up: [{ href: 'https://shop.example.test/wp-json/wc/v3/products/19' }],
  },
}

/** What WooCommerce sends for an address nobody filled in (`email` exists in `billing` only). */
export const EMPTY_ADDRESS = {
  first_name: '',
  last_name: '',
  company: '',
  address_1: '',
  address_2: '',
  city: '',
  state: '',
  postcode: '',
  country: '',
  phone: '',
}

const copy = (value: Json, overrides: Json): Json => ({ ...structuredClone(value), ...overrides })

export const rawOrder = (overrides: Json = {}) => copy(order, overrides)
export const rawSimpleProduct = (overrides: Json = {}) => copy(simpleProduct, overrides)
export const rawVariableProduct = (overrides: Json = {}) => copy(variableProduct, overrides)
export const rawVariation = (overrides: Json = {}) => copy(variation, overrides)

/** One line of `rawOrder()`, by position, with other values. */
export function rawLine(index: number, overrides: Json = {}): Json {
  const lines = order.line_items as Json[]
  return copy(lines[index]!, overrides)
}
